version: 2

build:
  # Required to get access to more recent Python versions.
  image: testing

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
